### Tarea P4 Fundamentos para Pyhton - Vectores, Arrays y Numpy

In [1]:
#Crear un Array de Enteros

In [2]:
import array as arr 
mi_array = arr.array('i',[1,15,45,95])
print(mi_array)

array('i', [1, 15, 45, 95])


In [1]:
dato = input("Indique un dato: ")

def una_coma(cadena):

    contador_comas = 0

    for caracter in cadena:

        if caracter == ',':

            contador_comas += 1

            if contador_comas > 1:

                return False

    if contador_comas == 1:

        return True

    else:

        return False

try:

    num = float(dato)

    if elemento.startswith('-') or num.is_integer():

        print("Dato ingresado es un número entero")

    else:

        print("Dato ingresado es un número con decimales")

except ValueError:

    if una_coma(dato):

        print("Dato ingresado es número con decimales")

    else:

        print("Dato ingresado es una cadena")
        

Indique un dato: 3,15,23
Dato ingresado es una cadena


In [6]:
nombre = 'Lucas Carballo'
print(nombre[:3])

print(nombre[-2:])

Luc
lo


In [15]:
#creo lista a partir de una cadena
aux = 'Caleidoscopio'
lista = list(aux)
print(lista)
#invierto la lista
lista.reverse()
print(lista)
#convierto lista en cadena
texto_reverso = ''.join(lista)
texto_reverso


['C', 'a', 'l', 'e', 'i', 'd', 'o', 's', 'c', 'o', 'p', 'i', 'o']
['o', 'i', 'p', 'o', 'c', 's', 'o', 'd', 'i', 'e', 'l', 'a', 'C']


'oipocsodielaC'

In [17]:
#crear funcion SUMA
def sumar(a,b):
    return a + b

sumar(2,3)

5

In [21]:
def imprimirSecuencia(*args):
    for arg in args:
        print(arg, end =' ')

imprimirSecuencia('Vamos','Argentina','todavia', '!')

Vamos Argentina todavia ! 

In [25]:
#funcion para calcular factorial de n
def factorial(n):
    if n == 0:
        return 1
    else:
        return n*factorial(n-1)
  
factorial(5)

120

In [1]:
#funcion para formatear un diccionario
def formatearDicc(diccionario):
    cadena = ""
    for clave, valor in diccionario.items():
        cadena += f"{clave}: {valor}\n"
        return cadena
    
diccionario={"nombre": "Lucas", "edad" : 34, "ciudad" : "Mendoza"}
print(formatearDicc(diccionario))

nombre: Lucas



In [29]:
# Pedir al usuario que ingrese un número y manejar
#cualquier excepción que se produzca

try:
    numero=int(input('Ingresa un numero'))
    print('El numero que ingresaste es:', numero)
except ValueError:
    print('lo que ingresaste no fue un numero')

Ingresa un numero22
El numero qu ingresaste es: 22


In [30]:
import numpy as nm
a = nm.array([1,3,5,7,9])
print(a)

[1 3 5 7 9]


In [31]:
v1 = nm.array([3,4,5])
v2 = nm.array([2,6,2])
producto_cruz = nm.cross(v1, v2)
print(producto_cruz)

[-22   4  10]


In [32]:
#calcular la media de un conjunto
media = nm.mean(a)
print(media)

5.0


In [33]:
a = 5
b = 3.5
c= a+b
print(type(c))

<class 'float'>


In [34]:
dato = -10

def una_coma(cadena):

    contador_comas = 0

    for caracter in cadena:

        if caracter == ',':

            contador_comas += 1

            if contador_comas > 1:

                return False

    if contador_comas == 1:

        return True

    else:

        return False

try:

    num = float(dato)

    if num.is_integer():

        print("Dato ingresado es un número entero")

    else:

        print("Dato ingresado es un número con decimales")

except ValueError:

    if una_coma(dato):

        print("Dato ingresado es número con decimales")

    else:

        print("Dato ingresado es una cadena")

Dato ingresado es un número entero


In [37]:
for i in range(1, 23):
    if i%3 == 0 and i % 5 ==0:
        print('Es multiplo de ambos, de 3 y de 5')
    elif i % 3 == 0 :
        print('Multiplo de 3')
    elif i % 5 == 0 :
        print('Multiplo de 5')
    else:
        print(i)

1
2
Multiplo de 3
4
Multiplo de 5
Multiplo de 3
7
8
Multiplo de 3
Multiplo de 5
11
Multiplo de 3
13
14
Es multiplo de ambos, de 3 y de 5
16
17
Multiplo de 3
19
Multiplo de 5
Multiplo de 3
22


In [10]:
#Calcular media de un conjunto
import numpy as np

my_set = np.array([2,6,9,10,5])
print('Mi conjunto es: ')
print(my_set)
print('La media de mi conjunto es:')
media = np.mean(my_set)
print(media)

Mi conjunto es: 
[ 2  6  9 10  5]
La media de mi conjunto es:
6.4


In [12]:
#Calcular la mediana del conjunto
mediana = np.median(my_set)
print('La mediana de mi conjunto es:')
print(mediana)

La mediana de mi conjunto es:
6.0


In [13]:
#Calcular la desviación estandar
desv_estandar = np.std(my_set)
print('La desviacion estandar es:')
print(desv_estandar)

La desviacion estandar es:
2.8705400188814645


In [15]:
frutas = ['manzana', 'banana', 'naranja', 'sandia', 'kiwi', 'melon', 'mandarina', 'pomelo', 'pera', 'manzana', 'naranja', 'banana']
print(frutas)
#convertir lista en matriz
matriz_frutas = np.array(frutas)
print(matriz_frutas)
#obtener los valores unicos de la matriz
frutas_unicas = np.unique(matriz_frutas)
print(frutas_unicas)
#obtener cantidad de cada fruta en la matriz
for frutas in frutas_unicas:
    cantidad = np.count_nonzero(matriz_frutas==frutas)
    print(f"{frutas}:{cantidad}")
    
    

['manzana', 'banana', 'naranja', 'sandia', 'kiwi', 'melon', 'mandarina', 'pomelo', 'pera', 'manzana', 'naranja', 'banana']
['manzana' 'banana' 'naranja' 'sandia' 'kiwi' 'melon' 'mandarina' 'pomelo'
 'pera' 'manzana' 'naranja' 'banana']
['banana' 'kiwi' 'mandarina' 'manzana' 'melon' 'naranja' 'pera' 'pomelo'
 'sandia']
banana:2
kiwi:1
mandarina:1
manzana:2
melon:1
naranja:2
pera:1
pomelo:1
sandia:1
